name: Example Destroy
on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - master
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    if:
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
    - uses: devopsmakers/pr-name-generator-action@v0.0.4
      id: generator
    - run: echo "Destroying ${{ steps.generator.outputs.name }}"
    - name: Create comment
      uses: peter-evans/create-or-update-comment@v2
      if: ${{ github.actor != 'dependabot[bot]' }}
      with:
        issue-number: ${{ github.event.number }}
        body: |
          Ephemeral environment: `${{ steps.generator.outputs.name }}` has been destroyed.
